//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStatu
    {
        public int StatusId { get; set; }
        public int UserId { get; set; }
        public bool StatusType { get; set; }
    
        public virtual User User { get; set; }
    }
}
